version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=prontolista
      - POSTGRES_USER=prontolista
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: "133506877714.dkr.ecr.eu-west-1.amazonaws.com/prontolista:${TAG}"
    ports:
      - 8000:8000
    env_file: .env
    entrypoint: /docker-entrypoint.sh

volumes:
  postgres-data:
