version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=prontolista
      - POSTGRES_USER=prontolista
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: "133506877714.dkr.ecr.eu-west-1.amazonaws.com/prontolista-nginx:${TAG}"
    ports:
      - 80:80
    volumes:
      - staticfiles:/static
    depends_on:
      - app

  app:
    image: "133506877714.dkr.ecr.eu-west-1.amazonaws.com/prontolista:${TAG}"
    volumes:
      - staticfiles:/app/prontolista/staticfiles
    env_file: .env
    entrypoint: /docker-entrypoint.sh

volumes:
  postgres-data:
  staticfiles:
