version: '3.7'

services:
  app:
    image: prontolista
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    entrypoint: /docker-entrypoint.sh
