version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=prontolista
      - POSTGRES_USER=prontolista

  app:
    image: prontolista
    build:
      context: .
      dockerfile: compose/django/Dockerfile-local
